library(sqldf)
elect <- read.csv.sql("household_power_consumption.txt",sql = "SELECT * FROM file WHEREhist Date = '1/2/2007' OR Date ='2/2/2007'",header = TRUE,sep=";")
elect$Datetime <- paste(elect$Date,elect$Time)
elect$Datetime <- strptime(elect$Datetime,format = "%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2),mar=c(4,4,2,1))
plot(elect$Datetime,elect$Global_active_power,type="l",xlab="",ylab = "Global Active Power(kilowatts)")
plot(elect$Datetime,elect$Voltage,type="l", xlab="datetime",ylab="Voltage")
plot(elect$Datetime,elect$Sub_metering_1,type="n",xlab="",ylab = "Energy sub metering")
points(elect$Datetime,elect$Sub_metering_1,type="l")
points(elect$Datetime,elect$Sub_metering_2,type="l",col="red")
points(elect$Datetime,elect$Sub_metering_3,type="l",col="blue")
legend("topright",lwd=1,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.5)
plot(elect$Datetime,elect$Global_reactive_power,type="l",xlab="datetime",ylab = "Global_reactive_power")
dev.copy(png,"plot4.png")
dev.off()